use_frameworks!

target 'OutcastID3_Example' do
  pod 'OutcastID3', :path => '../'

  target 'OutcastID3_Tests' do
    inherit! :search_paths

    
  end
end

target 'OutcastID3_Console_Example' do
    pod 'OutcastID3', :path => '../'
end
